---          
server:
  port: 1010

spring:
  profiles:
    active:
      - dev
---
spring:
  profiles: dev #开发环境
  application: 
    name: springcloud-dept-config-dev-client

eureka: #客户端注册进eureak的服务列表
  client:
    service-url:
      defaultZone: http://eureka8761.com:8761/eureka/ #注入的地址要的8761的一致 
      
server:
  port: 2020

---
spring:
  profiles:
    active:
      - test
---
spring:
  profiles: test #测试环境
  application:
    name: springcloud-dept-config-test-client
    
---
eureka: #客户端注册进eureak的服务列表
  client:
    service-url:
      defaultZone: http://eureka8761.com:8761/eureka/ #注入的地址要的8761的一致 
            
      
